# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09364dea30a3f7e03689c4fc6d478736b285f9d639e5b18f16dda49b252092b9a7fd5028a62963e5bcbc6506274c1d3329caa9dce0b66a2e8450978a561934d4

test:
  secret_key_base: 3e644d5d2a6b3107f181c98e751674aad0075fb443448662edde5f36b5c8da983fef06cc272e4afcfc9d342cbc2cce8363e4b54dd8ee6c44103804ac63f8fbda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
